//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendar.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOmer
    {
        public int Yom { get; set; }
        public string Sod1 { get; set; }
        public string Sod2 { get; set; }
        public string Teur { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string Picture { get; set; }
    }
}
