//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace name_search_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kid
    {
        public string FirstName { get; set; }
        public Nullable<double> Age { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string School { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> TimeOfEntry { get; set; }
    }
}
