//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntitiesDbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public string Name { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> PotatoKOrdered { get; set; }
        public Nullable<int> AppleCherryOrdered { get; set; }
        public Nullable<int> LukshenOrdered { get; set; }
        public Nullable<int> OnionOrdered { get; set; }
        public Nullable<int> CarrotLoafOrdered { get; set; }
        public int KishkeOrdered { get; set; }
        public string PriceOfOrder { get; set; }
        public System.DateTime DateOfOrder { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
